// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckzzhtpxelkxpufjyckv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrenpodHB4ZWxreHB1Zmp5Y2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTg4OTMsImV4cCI6MjA1Nzg5NDg5M30.md9JzPZUyhnhJJJZmyd8HSANNIV6QWtXgvFyDis8gSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);